% Please mannual load session a and session b
% This script is to merge a and b

% a.basic_para = basic_para;
% a.trial_para = trial_para;

% b.basic_para = basic_para;
% b.trial_para = trial_para;

a.basic_para;
a.trial_para;
b.basic_para;
b.trial_para;

c = struct;

trial_count_a = a.trial_para.trial_count;
trial_count_b = b.trial_para.trial_count;
trial_count_c = trial_count_a + trial_count_b;

%% Merge basic_para
c.basic_para = a.basic_para;

c.basic_para.randArray1 = ...
    [a.basic_para.randArray1(1:trial_count_a), b.basic_para.randArray1(1:end-trial_count_a)];
c.basic_para.randArray2 = ...
    [a.basic_para.randArray2(1:trial_count_a), b.basic_para.randArray2(1:end-trial_count_a)];
c.basic_para.randArray3 = ...
    [a.basic_para.randArray3(1:trial_count_a), b.basic_para.randArray3(1:end-trial_count_a)];
c.basic_para.randArray4 = ...
    [a.basic_para.randArray4(1:trial_count_a), b.basic_para.randArray4(1:end-trial_count_a)];
c.basic_para.randArray5 = ...
    [a.basic_para.randArray5(1:trial_count_a), b.basic_para.randArray5(1:end-trial_count_a)];
c.basic_para.ItiTime = ...
    [a.basic_para.ItiTime(1:trial_count_a), b.basic_para.ItiTime(1:end-trial_count_a)];
c.basic_para.preFixationTime = ...
    [a.basic_para.preFixationTime(1:trial_count_a), b.basic_para.preFixationTime(1:end-trial_count_a)];
c.basic_para.fixationTime = ...
    [a.basic_para.fixationTime(1:trial_count_a), b.basic_para.fixationTime(1:end-trial_count_a)];
c.basic_para.twoFixationTime = ...
    [a.basic_para.twoFixationTime(1:trial_count_a), b.basic_para.twoFixationTime(1:end-trial_count_a)];
c.basic_para.cumulativeErrorLimit = ...
    [a.basic_para.cumulativeErrorLimit(1:trial_count_a), b.basic_para.cumulativeErrorLimit(1:end-trial_count_a)];
c.basic_para.ifFreeTouch = ...
    [a.basic_para.ifFreeTouch(1:trial_count_a), b.basic_para.ifFreeTouch(1:end-trial_count_a)];

%% Merge trial_para
c.trial_para = a.trial_para;

c.trial_para.isGreenRectLeft = ...
    [a.trial_para.isGreenRectLeft(1:trial_count_a), b.trial_para.isGreenRectLeft(1:end-trial_count_a)];
c.trial_para.seq_length = ...
    [a.trial_para.seq_length(1:trial_count_a), b.trial_para.seq_length(1:end-trial_count_a)];
c.trial_para.numFrames = ...
    [a.trial_para.numFrames(1:trial_count_a), b.trial_para.numFrames(1:end-trial_count_a)];

c.trial_para.selecting_RT = ...
    [a.trial_para.selecting_RT, b.trial_para.selecting_RT];
c.trial_para.selecting_point = ...
    [a.trial_para.selecting_point, b.trial_para.selecting_point];
c.trial_para.ifSelectOffloading = ...
    [a.trial_para.ifSelectOffloading, b.trial_para.ifSelectOffloading];
c.trial_para.endingHold_RT = ...
    [a.trial_para.endingHold_RT, b.trial_para.endingHold_RT];
c.trial_para.isCorrect = ...
    [a.trial_para.isCorrect, b.trial_para.isCorrect];
c.trial_para.isIppatsuCorrect = ...
    [a.trial_para.isIppatsuCorrect, b.trial_para.isIppatsuCorrect];
c.trial_para.isTouchFrameCorrect = ...
    [a.trial_para.isTouchFrameCorrect, b.trial_para.isTouchFrameCorrect];
c.trial_para.isTouchingTimeOut = ...
    [a.trial_para.isTouchingTimeOut, b.trial_para.isTouchingTimeOut];
c.trial_para.cumulativeCorrect_greenRedSwitch = ...
    [a.trial_para.cumulativeCorrect_greenRedSwitch, b.trial_para.cumulativeCorrect_greenRedSwitch];
c.trial_para.consecutiveCorrect = ...
    [a.trial_para.consecutiveCorrect, b.trial_para.consecutiveCorrect];
c.trial_para.cumulativeError = ...
    [a.trial_para.cumulativeError, b.trial_para.cumulativeError];
c.trial_para.currentFrames = ...
    [a.trial_para.currentFrames, b.trial_para.currentFrames];
c.trial_para.currentSequence = ...
    [a.trial_para.currentSequence, b.trial_para.currentSequence];
c.trial_para.isFilled = ...
    [a.trial_para.isFilled, b.trial_para.isFilled];
c.trial_para.taskMode_noChoice_Green0_Red1 = ...
    [a.trial_para.taskMode_noChoice_Green0_Red1, b.trial_para.taskMode_noChoice_Green0_Red1];
c.trial_para.selectFlag_newSeq = ...
    [a.trial_para.selectFlag_newSeq, b.trial_para.selectFlag_newSeq];
c.trial_para.choiceMode = ...
    [a.trial_para.choiceMode, b.trial_para.choiceMode];
c.trial_para.choiceCondition_flag = ...
    [a.trial_para.choiceCondition_flag, b.trial_para.choiceCondition_flag];
c.trial_para.reCenterGazeBias_x = ...
    [a.trial_para.reCenterGazeBias_x, b.trial_para.reCenterGazeBias_x];
c.trial_para.reCenterGazeBias_y = ...
    [a.trial_para.reCenterGazeBias_y, b.trial_para.reCenterGazeBias_y];


c.trial_para.trial_count = a.trial_para.trial_count + b.trial_para.trial_count;
c.trial_para.uniqueSeq_trial_count = a.trial_para.uniqueSeq_trial_count + b.trial_para.uniqueSeq_trial_count;
c.trial_para.isWaitGocueBreak = zeros(1, c.trial_para.trial_count);
c.trial_para.isWaitGocueBreak(1:length(a.trial_para.isWaitGocueBreak)) = a.trial_para.isWaitGocueBreak;
c.trial_para.isWaitGocueBreak(trial_count_a+ (1:length(b.trial_para.isWaitGocueBreak)) ) = ...
    b.trial_para.isWaitGocueBreak;

c.trial_para.breakTime = ...
    [a.trial_para.breakTime, b.trial_para.breakTime];
c.trial_para.breakSeqLength = ...
    [a.trial_para.breakSeqLength, b.trial_para.breakSeqLength];

if false
    path = 'C:\ASDROOT\STUDY\backups\MATDATA_20220630\DnumFrames8_A\'; %#ok<UNRCH>
    fileName = 'DnumFrames8_A_of_2022-06-30trainDing_Step12_fixation_202005027C_forBehavior_6-merge.mat';
    basic_para = c.basic_para;
    trial_para = c.trial_para;
    save([path, fileName], 'basic_para', 'trial_para');
end